### PR TITLE
Separate isHtml & isGzipped

### PR DESCRIPTION
**Pull request by leveneg**
Fixes an issue in which `write` was getting called before `writeHead`,
before Harmon had a chance to determine if the request was for an HTML
or gzipped file.

Tests passing.

### CODE REVIEW

**Comment by leveneg** [comment]
why y'all havin travis use v0.1? 😂

**Comment by leveneg** [comment]
Hi plz lmk if there's anything I can do to help this along :)

**Comment by nival999** [comment]
The doge.js example still isn't working

**Comment by unixfox** [comment]
@No9  Can this PR be merged? This fixed the issue #46 I tested it works.

**Comment by redoxate** [comment]
@No9  Can this PR be merged? It fixes the issue #46.
@leveneg Thanks <3

**Comment by leveneg** [comment]
🎉 thanks @No9

**Comment by davidgoitia** [comment]
@No9 can you publish the npm package?

**Comment by No9** [comment]
@davidgoitia Pushed as 1.4.4 
This package needs some love as I tried to upgrade some of the deps but I got failures so I left them as they were.

**Pull request merged**
