### PR TITLE
Working with Content-Encoding=gzip

### PR DESCRIPTION
**Pull request by sergiator**
This changes allows to work with gzip-encoded pages, but I have doubts:
1) should I  compress outer data with gzip again to match initial content-encoding header?
2) should I implement support for other compressing types?
3) maybe, the better place for this changes is another middleware?

### CODE REVIEW

**Comment by No9** [comment]
Cool thanks for this. 
Will look at it over the weekend :)

**Comment by No9** [comment]
Hi @sergiator had a dive into this and looks it looks ok. 

My sentiment was that it should be done in other middleware but we get so many new users asking for this that I am prepared to take it in. 

Can you provide tests for it please and update the contributor list at the bottom of the readme. 

Thanks

**Comment by sergiator** [comment]
Hi @No9!

Thank you for reply. I'll try to write tests asap

**Comment by sergiator** [comment]
I done it. Sorry for lot of commits. There was a small war for correct number of white spaces )))

**Comment by No9** [comment]
Wow thanks for the example too :+1:  
That's fantastic. 
Will dive in over in the next couple of hours to get this out.

**Pull request merged**
