### PR TITLE
Removing duplicate http require statement.

### PR DESCRIPTION
**Pull request by gnrlbzik**
Removed duplicated line.

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
Nice catch ;)

**Comment by gnrlbzik** [comment]
hey, little things count : )

**Comment by No9** [comment]
Thanks @fabiosantoscode 
Just notices that you and @smazurov are not on the NPM maintainers list. 
Can you confirm your NPM usernames and I can add you in there so you can push too :)

**Comment by fabiosantoscode** [comment]
Here:
https://www.npmjs.com/~fabiosantoscode

**Comment by No9** [comment]
Done

**Pull request merged**
